#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
# List of local libraries
SEARCH_BMI160_driver=./libs/BMI160_driver
SEARCH_BMM150-Sensor-API=./libs/BMM150-Sensor-API
SEARCH_cat1cm0p=./libs/cat1cm0p
SEARCH_cmsis=./libs/cmsis
SEARCH_core-lib=./libs/core-lib
SEARCH_core-make=./libs/core-make
SEARCH_mtb-hal-cat1=./libs/mtb-hal-cat1
SEARCH_mtb-pdl-cat1=./libs/mtb-pdl-cat1
SEARCH_recipe-make-cat1a=./libs/recipe-make-cat1a
SEARCH_retarget-io=./libs/retarget-io
SEARCH_sensor-orientation-bmx160=./libs/sensor-orientation-bmx160
SEARCH_sensor-xensiv-dps3xx=./libs/sensor-xensiv-dps3xx
SEARCH_serial-flash=./libs/serial-flash


# Path to the current BSP
SEARCH_TARGET_APP_CY8CKIT-062S2-43012=bsps/TARGET_APP_CY8CKIT-062S2-43012

# The search paths for the included middleware

# Search libraries added to build
SEARCH_MTB_MK+=$(SEARCH_BMI160_driver)
SEARCH_MTB_MK+=$(SEARCH_BMM150-Sensor-API)
SEARCH_MTB_MK+=$(SEARCH_cat1cm0p)
SEARCH_MTB_MK+=$(SEARCH_cmsis)
SEARCH_MTB_MK+=$(SEARCH_core-lib)
SEARCH_MTB_MK+=$(SEARCH_core-make)
SEARCH_MTB_MK+=$(SEARCH_mtb-hal-cat1)
SEARCH_MTB_MK+=$(SEARCH_mtb-pdl-cat1)
SEARCH_MTB_MK+=$(SEARCH_recipe-make-cat1a)
SEARCH_MTB_MK+=$(SEARCH_retarget-io)
SEARCH_MTB_MK+=$(SEARCH_sensor-orientation-bmx160)
SEARCH_MTB_MK+=$(SEARCH_sensor-xensiv-dps3xx)
SEARCH_MTB_MK+=$(SEARCH_serial-flash)

-include $(CY_INTERNAL_APP_PATH)/importedbsp.mk
COMPONENTS += MW_BMI160_DRIVER
COMPONENTS += MW_BMM150_SENSOR_API
COMPONENTS += MW_CAT1CM0P
COMPONENTS += MW_CMSIS
COMPONENTS += MW_CORE_LIB
COMPONENTS += MW_CORE_MAKE
COMPONENTS += MW_MTB_HAL_CAT1
COMPONENTS += MW_MTB_PDL_CAT1
COMPONENTS += MW_RECIPE_MAKE_CAT1A
COMPONENTS += MW_RETARGET_IO
COMPONENTS += MW_SENSOR_ORIENTATION_BMX160
COMPONENTS += MW_SENSOR_XENSIV_DPS3XX
COMPONENTS += MW_SERIAL_FLASH

# Register map file
DEVICE_CY8C624ABZI-S2D44_SVD=$(SEARCH_mtb-pdl-cat1)/devices/COMPONENT_CAT1A/svd/psoc6_02.svd


#
# generate make targets for the graphical editors that are specific to this project
#

modlibs:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name library-manager
.PHONY: modlibs

library-manager:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name library-manager
.PHONY: library-manager

qspi-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name qspi-configurator
.PHONY: qspi-configurator

config:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name device-configurator
.PHONY: config

device-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name device-configurator
.PHONY: device-configurator

capsense-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name capsense-configurator
.PHONY: capsense-configurator

capsense-tuner:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name capsense-tuner
.PHONY: capsense-tuner

seglcd-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name seglcd-configurator
.PHONY: seglcd-configurator

bsp-assistant:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bsp-assistant
.PHONY: bsp-assistant

config_bt:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bt-configurator
.PHONY: config_bt

bt-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bt-configurator
.PHONY: bt-configurator

config_usbdev:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name usbdev-configurator
.PHONY: config_usbdev

usbdev-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name usbdev-configurator
.PHONY: usbdev-configurator

smartio-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name smartio-configurator
.PHONY: smartio-configurator

config_lin:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name lin-configurator
.PHONY: config_lin

lin-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name lin-configurator
.PHONY: lin-configurator

